version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/taski-backend:latest
    ports:
      - "8000:8000"

  nginx:
    image: ${{ secrets.DOCKER_USERNAME }}/taski-nginx:latest
    ports:
      - "80:80"
